In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
df = pd.read_csv('/content/drug200.csv')

###Task 1: Read the dataset and do data pre-processing

In [41]:
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [42]:
df['Drug'].unique()

array(['DrugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [43]:
df.isnull()

Age    Sex     BP  Cholesterol  Na_to_K   Drug
0    False  False  False        False    False  False
1    False  False  False        False    False  False
2    False  False  False        False    False  False
3    False  False  False        False    False  False
4    False  False  False        False    False  False
..     ...    ...    ...          ...      ...    ...
195  False  False  False        False    False  False
196  False  False  False        False    False  False
197  False  False  False        False    False  False
198  False  False  False        False    False  False
199  False  False  False        False    False  False

[200 rows x 6 columns]

In [44]:
x=pd.get_dummies(df.iloc[:,2:5]).values
x

array([[25.355,  1.   ,  0.   ,  0.   ,  1.   ,  0.   ],
       [13.093,  0.   ,  1.   ,  0.   ,  1.   ,  0.   ],
       [10.114,  0.   ,  1.   ,  0.   ,  1.   ,  0.   ],
       ...,
       [ 9.894,  0.   ,  0.   ,  1.   ,  1.   ,  0.   ],
       [14.02 ,  0.   ,  0.   ,  1.   ,  0.   ,  1.   ],
       [11.349,  0.   ,  1.   ,  0.   ,  0.   ,  1.   ]])

In [45]:
y=pd.get_dummies(df['Drug']).values
y

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 1,

###Task 2: Build the ANN model with (input layer, min 3 hidden layers & output layer)


In [46]:
from sklearn.model_selection import train_test_split

In [47]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.30,random_state=15)

In [48]:

xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((140, 6), (60, 6), (140, 5), (60, 5))

In [60]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

In [61]:
#intialize the sequence model
model=Sequential()
model.add(Dense(5,activation='relu'))
model.add(Dense(60,activation='relu'))
model.add(Dense(31,activation='relu'))
model.add(Dense(29,activation='relu'))
model.add(Dense(19,activation='relu'))
model.add(Dense(5,activation='softmax'))

In [62]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [63]:
# Training the model
model.fit(xtrain,ytrain,batch_size=4,epochs=10,validation_data=(xtest,ytest))

Epoch 1/10
35/35 [==============================] - 2s 13ms/step - loss: 1.1860 - accuracy: 0.4643 - val_loss: 1.2008 - val_accuracy: 0.4333
Epoch 2/10
35/35 [==============================] - 0s 5ms/step - loss: 1.1631 - accuracy: 0.4643 - val_loss: 1.1883 - val_accuracy: 0.4333
Epoch 3/10
35/35 [==============================] - 0s 6ms/step - loss: 1.1495 - accuracy: 0.4643 - val_loss: 1.1531 - val_accuracy: 0.4333
Epoch 4/10
35/35 [==============================] - 0s 5ms/step - loss: 1.1172 - accuracy: 0.4643 - val_loss: 1.1374 - val_accuracy: 0.4333
Epoch 5/10
35/35 [==============================] - 0s 6ms/step - loss: 1.1002 - accuracy: 0.4786 - val_loss: 1.1132 - val_accuracy: 0.4833
Epoch 6/10
35/35 [==============================] - 0s 6ms/step - loss: 1.0740 - accuracy: 0.5429 - val_loss: 1.1007 - val_accuracy: 0.4500
Epoch 7/10
35/35 [==============================] - 0s 6ms/step - loss: 1.0508 - accuracy: 0.5571 - val_loss: 1.0793 - val_accuracy: 0.4667
Epoch 8/10
35/35 [=

In [64]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_41 (Dense)            (4, 5)                    35        
                                                                 
 dense_42 (Dense)            (4, 60)                   360       
                                                                 
 dense_43 (Dense)            (4, 31)                   1891      
                                                                 
 dense_44 (Dense)            (4, 29)                   928       
                                                                 
 dense_45 (Dense)            (4, 19)                   570       
                                                                 
 dense_46 (Dense)            (4, 5)                    100       
                                                                 
Total params: 3,884
Trainable params: 3,884
Non-traina

###Task 3: Test the model with random data

In [59]:
model.predict([[23,0,1,0,1,0]])

1/1 [==============================] - 0s 136ms/step


array([[0.885324  , 0.03563827, 0.04854133, 0.00945829, 0.02103815]],
      dtype=float32)